#!/bin/zsh
# On-login settings.

# set up XDG directories
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# append local bin to path
export PATH=$HOME/bin:$HOME/.local/bin:$PATH

# environment configuration for some programs
export R_LIBS_USER=$HOME/.local/lib/R
export GOPATH=$HOME/.go
export TEXMFHOME=$XDG_DATA_HOME/texmf
export TEXMFVAR=$XDG_CACHE_HOME/texmf
export TEXMFCONFIG=$XDG_CONFIG_HOME/texmf
export ICEAUTHORITY=$XDG_CACHE_HOME/ICEauthority
export RLWRAP_HOME=$XDG_CACHE_HOME/rlwrap
export TERMINFO=$XDG_DATA_HOME/terminfo
export TERMINFO_DIRS=$TERMINFO:/usr/share/terminfo
export XAUTHORITY=$XDG_DATA_HOME/xorg/xauthority
export PYTHONSTARTUP=$XDG_CONFIG_HOME/python/pythonrc
export IPYTHONDIR=$XDG_CONFIG_HOME/python/ipython
export JUPYTER_CONFIG_DIR=$XDG_CONFIG_HOME/python/jupyter
export QT_SCALE_FACTOR=1.2
export _JAVA_AWT_WM_NONREPARENTING=1 # fixes java programs
export NO_AT_BRIDGE=1 # fixes some gtk warnings
